HEADER_PROTEIN = 'protein id'
HEADER_PROTEINS = 'protein group ids'
HEADER_GENEID = 'gene'
HEADER_GENENAME = 'gene name'
HEADER_DESCRIPTION = 'description'
HEADER_COVERAGE = 'coverage'
HEADER_NO_UNIPEP = '# unique peptides'
HEADER_NO_PEPTIDE = '# peptides'
HEADER_NO_PSM = '# psms'
HEADER_AREA = 'intensity'
HEADER_QVAL = 'q-value'
HEADER_PEP = 'PEP'
HEADER_SAMPLES = "samples"
HEADER_IBAQ = "ibaq"